/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.JugadorController;
import controller.PosicionController;
import controller.TorneoController;


import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import model.Equipo;
import model.Jugador;
import model.Municipio;
import model.Posicion;

/**
 *
 * @author washi
 */
public class FrmTorneo extends javax.swing.JFrame {

    /**
     * Creates new form FrmTorneo
     */
    public FrmTorneo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTorneo = new javax.swing.JTabbedPane();
        jpMunicipo = new javax.swing.JPanel();
        lbIdMunicipio = new javax.swing.JLabel();
        lbNombreMunicipio = new javax.swing.JLabel();
        txtIdMunicipio = new javax.swing.JTextField();
        txtNombreMunicipio = new javax.swing.JTextField();
        btnCrearMunicipio = new javax.swing.JButton();
        btnBuscarMunicipio = new javax.swing.JButton();
        btnActualizarMunicipio = new javax.swing.JButton();
        btnEliminarMunicipio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMunicipios = new javax.swing.JTable();
        jpEquipo = new javax.swing.JPanel();
        lbIdEquipo = new javax.swing.JLabel();
        lbNombreEquipo = new javax.swing.JLabel();
        lbDtEquipo = new javax.swing.JLabel();
        lbMunicipioEquipo = new javax.swing.JLabel();
        txtIdEquipo = new javax.swing.JTextField();
        txtNombreEquipo = new javax.swing.JTextField();
        txtDtEquipo = new javax.swing.JTextField();
        cbxMunicipios = new javax.swing.JComboBox<>();
        btnCrearEquipo = new javax.swing.JButton();
        btnBuscarEquipo = new javax.swing.JButton();
        btnActualizarEquipo = new javax.swing.JButton();
        btnEliminarEquipo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEquipos = new javax.swing.JTable();
        jpPosicion = new javax.swing.JPanel();
        jpMunicipo1 = new javax.swing.JPanel();
        lbIdPosicion = new javax.swing.JLabel();
        lbNombrePosicion = new javax.swing.JLabel();
        txtIdPosicion = new javax.swing.JTextField();
        txtNombrePosicion = new javax.swing.JTextField();
        btnCrearPosicion = new javax.swing.JButton();
        btnBuscarPosicion = new javax.swing.JButton();
        btnActualizarPosicion = new javax.swing.JButton();
        btnEliminarPosicion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPosiciones = new javax.swing.JTable();
        jpJugador = new javax.swing.JPanel();
        lbIdJugador = new javax.swing.JLabel();
        txtIdJugador = new javax.swing.JTextField();
        btnCrearJugador = new javax.swing.JButton();
        btnBuscarJugador = new javax.swing.JButton();
        lbNombreJugador = new javax.swing.JLabel();
        txtNombreJugador = new javax.swing.JTextField();
        btnActualizarJugador = new javax.swing.JButton();
        btnEliminarJugador = new javax.swing.JButton();
        lbEquipoJugador = new javax.swing.JLabel();
        cbxEquipoJugador = new javax.swing.JComboBox<>();
        lbPosicionJugador = new javax.swing.JLabel();
        cbxPosicionJugador = new javax.swing.JComboBox<>();
        lbNumeroJugador = new javax.swing.JLabel();
        txtNumeroJugador = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpTorneoMouseClicked(evt);
            }
        });

        lbIdMunicipio.setText("Id Municipio");

        lbNombreMunicipio.setText("Nombre Municipio");

        btnCrearMunicipio.setText("Crear");
        btnCrearMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMunicipioActionPerformed(evt);
            }
        });

        btnBuscarMunicipio.setText("Buscar");
        btnBuscarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMunicipioActionPerformed(evt);
            }
        });

        btnActualizarMunicipio.setText("Actualizar");
        btnActualizarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMunicipioActionPerformed(evt);
            }
        });

        btnEliminarMunicipio.setText("Eliminar");
        btnEliminarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMunicipioActionPerformed(evt);
            }
        });

        tblMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMunicipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMunicipiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMunicipios);

        javax.swing.GroupLayout jpMunicipoLayout = new javax.swing.GroupLayout(jpMunicipo);
        jpMunicipo.setLayout(jpMunicipoLayout);
        jpMunicipoLayout.setHorizontalGroup(
            jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMunicipoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMunicipoLayout.createSequentialGroup()
                        .addComponent(lbIdMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpMunicipoLayout.createSequentialGroup()
                        .addComponent(lbNombreMunicipio)
                        .addGap(6, 6, 6)))
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombreMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(txtIdMunicipio))
                .addGap(18, 18, 18)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMunicipoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMunicipio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMunicipoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBuscarMunicipio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMunicipoLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        jpMunicipoLayout.setVerticalGroup(
            jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMunicipoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdMunicipio)
                    .addComponent(txtIdMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearMunicipio)
                    .addComponent(btnBuscarMunicipio))
                .addGap(18, 18, 18)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreMunicipio)
                    .addComponent(txtNombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarMunicipio)
                    .addComponent(btnEliminarMunicipio))
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMunicipoLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );

        jpTorneo.addTab("Municipio", jpMunicipo);

        lbIdEquipo.setText("Id equipo");

        lbNombreEquipo.setText("Nombre Equipo");

        lbDtEquipo.setText("D.T. Equipo");

        lbMunicipioEquipo.setText("Municipio Equipo");

        cbxMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMunicipiosActionPerformed(evt);
            }
        });

        btnCrearEquipo.setText("Crear");
        btnCrearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEquipoActionPerformed(evt);
            }
        });

        btnBuscarEquipo.setText("Buscar");
        btnBuscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEquipoActionPerformed(evt);
            }
        });

        btnActualizarEquipo.setText("Actualizar");
        btnActualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEquipoActionPerformed(evt);
            }
        });

        btnEliminarEquipo.setText("Borrar");
        btnEliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEquipoActionPerformed(evt);
            }
        });

        tblEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEquiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEquipos);

        javax.swing.GroupLayout jpEquipoLayout = new javax.swing.GroupLayout(jpEquipo);
        jpEquipo.setLayout(jpEquipoLayout);
        jpEquipoLayout.setHorizontalGroup(
            jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEquipoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEquipoLayout.createSequentialGroup()
                        .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreEquipo)
                            .addComponent(lbDtEquipo))
                        .addGap(18, 18, 18)
                        .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEquipoLayout.createSequentialGroup()
                                .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarEquipo))
                            .addComponent(txtDtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarEquipo)
                            .addGroup(jpEquipoLayout.createSequentialGroup()
                                .addComponent(lbIdEquipo)
                                .addGap(44, 44, 44)
                                .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnBuscarEquipo)))
                        .addGroup(jpEquipoLayout.createSequentialGroup()
                            .addComponent(lbMunicipioEquipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEquipoLayout.setVerticalGroup(
            jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEquipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdEquipo)
                    .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearEquipo)
                    .addComponent(btnBuscarEquipo))
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreEquipo)
                    .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarEquipo)
                    .addComponent(btnEliminarEquipo))
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDtEquipo)
                    .addComponent(txtDtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMunicipioEquipo)
                    .addComponent(cbxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpTorneo.addTab("Equipo", jpEquipo);

        lbIdPosicion.setText("Id Posicion");

        lbNombrePosicion.setText("Nombre Posicion");

        btnCrearPosicion.setText("Crear");
        btnCrearPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPosicionActionPerformed(evt);
            }
        });

        btnBuscarPosicion.setText("Buscar");
        btnBuscarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPosicionActionPerformed(evt);
            }
        });

        btnActualizarPosicion.setText("Actualizar");
        btnActualizarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPosicionActionPerformed(evt);
            }
        });

        btnEliminarPosicion.setText("Eliminar");
        btnEliminarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPosicionActionPerformed(evt);
            }
        });

        tblPosiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPosiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPosicionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPosiciones);

        javax.swing.GroupLayout jpMunicipo1Layout = new javax.swing.GroupLayout(jpMunicipo1);
        jpMunicipo1.setLayout(jpMunicipo1Layout);
        jpMunicipo1Layout.setHorizontalGroup(
            jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMunicipo1Layout.createSequentialGroup()
                .addGroup(jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMunicipo1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMunicipo1Layout.createSequentialGroup()
                                .addComponent(lbIdPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jpMunicipo1Layout.createSequentialGroup()
                                .addComponent(lbNombrePosicion)
                                .addGap(6, 6, 6)))
                        .addGroup(jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombrePosicion, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(txtIdPosicion))
                        .addGap(18, 18, 18)
                        .addGroup(jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrearPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizarPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMunicipo1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarPosicion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMunicipo1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnBuscarPosicion))))
                    .addGroup(jpMunicipo1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMunicipo1Layout.setVerticalGroup(
            jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMunicipo1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdPosicion)
                    .addComponent(txtIdPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearPosicion)
                    .addComponent(btnBuscarPosicion))
                .addGap(18, 18, 18)
                .addGroup(jpMunicipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombrePosicion)
                    .addComponent(txtNombrePosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarPosicion)
                    .addComponent(btnEliminarPosicion))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPosicionLayout = new javax.swing.GroupLayout(jpPosicion);
        jpPosicion.setLayout(jpPosicionLayout);
        jpPosicionLayout.setHorizontalGroup(
            jpPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(jpPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpPosicionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpMunicipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpPosicionLayout.setVerticalGroup(
            jpPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
            .addGroup(jpPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpPosicionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpMunicipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpTorneo.addTab("Posicion", jpPosicion);

        lbIdJugador.setText("Id Jugador");

        btnCrearJugador.setText("Crear");
        btnCrearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearJugadorActionPerformed(evt);
            }
        });

        btnBuscarJugador.setText("Buscar");
        btnBuscarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJugadorActionPerformed(evt);
            }
        });

        lbNombreJugador.setText("Nombre Jugador");

        btnActualizarJugador.setText("Actualizar");
        btnActualizarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarJugadorActionPerformed(evt);
            }
        });

        btnEliminarJugador.setText("Eliminar");
        btnEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJugadorActionPerformed(evt);
            }
        });

        lbEquipoJugador.setText("Equipo");

        cbxEquipoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEquipoJugadorActionPerformed(evt);
            }
        });

        lbPosicionJugador.setText("Posicion");

        lbNumeroJugador.setText("Numero Jugador");

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJugadoresMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblJugadores);

        javax.swing.GroupLayout jpJugadorLayout = new javax.swing.GroupLayout(jpJugador);
        jpJugador.setLayout(jpJugadorLayout);
        jpJugadorLayout.setHorizontalGroup(
            jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpJugadorLayout.createSequentialGroup()
                        .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpJugadorLayout.createSequentialGroup()
                                .addComponent(lbNumeroJugador)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroJugador))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpJugadorLayout.createSequentialGroup()
                                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIdJugador)
                                    .addComponent(lbNombreJugador)
                                    .addComponent(lbEquipoJugador)
                                    .addComponent(lbPosicionJugador))
                                .addGap(18, 18, 18)
                                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(cbxEquipoJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxPosicionJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(45, 45, 45)
                        .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarJugador)
                            .addComponent(btnCrearJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarJugador)
                            .addComponent(btnBuscarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jpJugadorLayout.setVerticalGroup(
            jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpJugadorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdJugador)
                    .addComponent(txtIdJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearJugador)
                    .addComponent(btnBuscarJugador))
                .addGap(18, 18, 18)
                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreJugador)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarJugador)
                    .addComponent(btnEliminarJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeroJugador)
                    .addComponent(txtNumeroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEquipoJugador)
                    .addComponent(cbxEquipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPosicionJugador)
                    .addComponent(cbxPosicionJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpTorneo.addTab("Jugador", jpJugador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    TorneoController controlador = new TorneoController();
    PosicionController posicionController = new PosicionController();
    JugadorController jugadorController = new JugadorController();
    
    private void formWindowOpened(java.awt.event.WindowEvent evt){
        llenarTablaMunicipios();
        llenarComboMunicipios();
        llenarComboEquipos();
        llenarComboPosiciones();
        llenarTablaEquipos();
        llenarTablaPosiciones();
    }
    
    private void tblMunicipiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMunicipiosMouseClicked
        // TODO add your handling code here:
        int fila = tblMunicipios.getSelectedRow();
        int id = (int) tblMunicipios.getValueAt(fila, 0);
        Municipio municipio = controlador.findMunicipio(id);
        txtIdMunicipio.setText("" + municipio.id);
        txtNombreMunicipio.setText(municipio.nombre);
        llenarTablaMunicipios();
    }//GEN-LAST:event_tblMunicipiosMouseClicked

    private void btnCrearMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMunicipioActionPerformed
        String nombre = txtNombreMunicipio.getText();
        boolean seInserto = controlador.insertMunicipio(nombre);
        if (seInserto){
            JOptionPane.showMessageDialog(this,"el municipio se inserto correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al insertar el municipio");
        }
        llenarTablaMunicipios(); 
        llenarComboMunicipios();
    }//GEN-LAST:event_btnCrearMunicipioActionPerformed

    private void btnBuscarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMunicipioActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdMunicipio.getText());
        Municipio municipio = controlador.findMunicipio(id);
        if(municipio == null){
            JOptionPane.showMessageDialog(this, "El municipio no fue encontrado!");
        }else{
            txtNombreMunicipio.setText(municipio.nombre);
        }
    }//GEN-LAST:event_btnBuscarMunicipioActionPerformed

    private void btnActualizarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMunicipioActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdMunicipio.getText());
        String nombre = txtNombreMunicipio.getText();
        boolean seActualizo = controlador.updateMunicipio(id, nombre);
        if (seActualizo){
            JOptionPane.showMessageDialog(this, "El municipio se actualizó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error el municipio no se actualizó!");
        }
        llenarTablaMunicipios(); 
        llenarComboMunicipios();
    }//GEN-LAST:event_btnActualizarMunicipioActionPerformed

    private void btnEliminarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMunicipioActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdMunicipio.getText());
        if (controlador.deleteMunicipio(id)){
            JOptionPane.showMessageDialog(this, "El municipio se eliminó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error el municipio no se eliminó!");
        }
        llenarTablaMunicipios();           
        llenarComboMunicipios();
    }//GEN-LAST:event_btnEliminarMunicipioActionPerformed

    private void btnCrearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEquipoActionPerformed
        // TODO add your handling code here:
        
        String nombre = txtNombreEquipo.getText();
        String dt = txtDtEquipo.getText();
        Municipio municipio = (Municipio)(cbxMunicipios.getSelectedItem());
        int id_municipio = municipio.id;
        boolean seInserto = controlador.insertEquipo(nombre, dt, id_municipio);
        if (seInserto){
            JOptionPane.showMessageDialog(this,"El equipo se inserto correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al insertar el equipo");
        }
        
        llenarTablaEquipos();
       
    }//GEN-LAST:event_btnCrearEquipoActionPerformed

    private void cbxMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMunicipiosActionPerformed
        // TODO add your handling code here:
        //llenarComboMunicipios();
    }//GEN-LAST:event_cbxMunicipiosActionPerformed

    private void tblEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquiposMouseClicked
        // TODO add your handling code here:
        int fila = tblEquipos.getSelectedRow();
        int id = (int) tblEquipos.getValueAt(fila, 0);
        Equipo equipo = controlador.findEquipo(id);
        txtIdEquipo.setText("" + equipo.id);
        txtNombreEquipo.setText(equipo.nombre);
        txtDtEquipo.setText(equipo.dt);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbxMunicipios.getModel();
        for(int i = 0; i < modelo.getSize(); i++){
            Municipio municipio = (Municipio) modelo.getElementAt(i);
            if(municipio.id == equipo.id_municipio){
                cbxMunicipios.setSelectedItem(municipio);
                break;
            }
        }
        
    }//GEN-LAST:event_tblEquiposMouseClicked

    private void jpTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTorneoMouseClicked
        // TODO add your handling code here:
        llenarTablaMunicipios();
        llenarComboMunicipios();
        llenarTablaEquipos();
        llenarTablaPosiciones();
        llenarTablaJugadores();


    }//GEN-LAST:event_jpTorneoMouseClicked

    private void btnBuscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEquipoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdEquipo.getText());
        Equipo equipo = controlador.findEquipo(id);
        txtNombreEquipo.setText(equipo.nombre);
        txtDtEquipo.setText(equipo.dt);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbxMunicipios.getModel();
        for(int i = 0; i < modelo.getSize(); i++){
            Municipio municipio = (Municipio) modelo.getElementAt(i);
            if(municipio.id == equipo.id_municipio){
                cbxMunicipios.setSelectedItem(municipio);
                break;
            }
        }
    }//GEN-LAST:event_btnBuscarEquipoActionPerformed

    
      
        
    private void btnActualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEquipoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdEquipo.getText());
        String nombre = txtNombreEquipo.getText();
        String dt = txtDtEquipo.getText();
        Municipio municipio = (Municipio)(cbxMunicipios.getSelectedItem());
        int id_municipio = municipio.id;
        boolean seActualizo = controlador.updateEquipo(id, nombre, dt, id_municipio);
        if (seActualizo){
            JOptionPane.showMessageDialog(this,"El equipo se actualizó correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al actualizar el equipo");
        }
        
        llenarTablaEquipos();        llenarTablaEquipos();

    }//GEN-LAST:event_btnActualizarEquipoActionPerformed

    private void btnEliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEquipoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdEquipo.getText());
        if (controlador.deleteEquipo(id)){
            JOptionPane.showMessageDialog(this, "El Equipo se eliminó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error el Equipo no se eliminó!");
        }
        llenarTablaEquipos();
        llenarComboMunicipios();
    }//GEN-LAST:event_btnEliminarEquipoActionPerformed

    private void btnCrearPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPosicionActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombrePosicion.getText();
        boolean seInserto = posicionController.insertPosicion(nombre);
        if (seInserto){
            JOptionPane.showMessageDialog(this,"La posicion se inserto correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al insertar la posicion");
        }
        llenarTablaPosiciones(); 
        llenarComboPosiciones();
    }//GEN-LAST:event_btnCrearPosicionActionPerformed

    private void btnBuscarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPosicionActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdPosicion.getText());
        Posicion posicion = posicionController.findPosicion(id);
        if(posicion == null){
            JOptionPane.showMessageDialog(this, "La posicion no fue encontrada!");
        }else{
            txtNombrePosicion.setText(posicion.nombre);
        }       
    }//GEN-LAST:event_btnBuscarPosicionActionPerformed

    private void btnActualizarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPosicionActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdPosicion.getText());
        String nombre = txtNombrePosicion.getText();
        boolean seActualizo = posicionController.updatePosicion(id, nombre);
        if (seActualizo){
            JOptionPane.showMessageDialog(this, "La posición se actualizó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error la posicion no se actualizó!");
        }
        llenarTablaPosiciones(); 
        llenarComboPosiciones();        
    }//GEN-LAST:event_btnActualizarPosicionActionPerformed

    private void btnEliminarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPosicionActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdPosicion.getText());
        if (posicionController.deletePosicion(id)){
            JOptionPane.showMessageDialog(this, "La posición se eliminó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error la posición no se eliminó!");
        }
        llenarTablaPosiciones();           
        llenarComboPosiciones();        
        
    }//GEN-LAST:event_btnEliminarPosicionActionPerformed

    private void tblPosicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPosicionesMouseClicked
        // TODO add your handling code here:
        int fila = tblPosiciones.getSelectedRow();
        int id = (int) tblPosiciones.getValueAt(fila, 0);
        Posicion posicion = posicionController.findPosicion(id);
        txtIdPosicion.setText("" + posicion.id);
        txtNombrePosicion.setText(posicion.nombre);
        llenarTablaPosiciones();         
    }//GEN-LAST:event_tblPosicionesMouseClicked

    private void btnCrearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearJugadorActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreJugador.getText();
        String numero = txtNumeroJugador.getText();
        Equipo equipo = (Equipo)(cbxEquipoJugador.getSelectedItem());
        int id_equipo = equipo.id;
        Posicion posicion = (Posicion)(cbxPosicionJugador.getSelectedItem());
        int id_posicion = posicion.id;
        
        boolean seInserto = jugadorController.insertJugador(nombre, numero, id_equipo, id_posicion);
        if (seInserto){
            JOptionPane.showMessageDialog(this,"El jugador se inserto correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al insertar el jugador");
        }
        
        llenarTablaEquipos();
        
        


    }//GEN-LAST:event_btnCrearJugadorActionPerformed

    private void btnBuscarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJugadorActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdJugador.getText());
        Jugador jugador = jugadorController.findJugador(id);
        txtNombreJugador.setText(jugador.nombre);
        txtNumeroJugador.setText(jugador.numero);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbxEquipoJugador.getModel();
        for(int i = 0; i < modelo.getSize(); i++){
            Equipo equipo = (Equipo) modelo.getElementAt(i);
            if(equipo.id == jugador.id_equipo){
                cbxEquipoJugador.setSelectedItem(equipo);
                break;
            }
        }
        
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cbxPosicionJugador.getModel();
        for(int i = 0; i < modelo1.getSize(); i++){
            Posicion posicion = (Posicion) modelo1.getElementAt(i);
            if(posicion.id == jugador.id_posicion){
                cbxPosicionJugador.setSelectedItem(posicion);
                break;
            }
        }        
    }//GEN-LAST:event_btnBuscarJugadorActionPerformed

    private void btnActualizarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarJugadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnActualizarJugadorActionPerformed

    private void btnEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJugadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEliminarJugadorActionPerformed

    private void tblJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJugadoresMouseClicked
        // TODO add your handling code here:
        int fila = tblJugadores.getSelectedRow();
        int id = (int) tblJugadores.getValueAt(fila, 0);
        Jugador jugador = jugadorController.findJugador(id);
        txtIdJugador.setText("" + jugador.id);
        txtNombreJugador.setText(jugador.nombre);
        llenarTablaJugadores();              
    }//GEN-LAST:event_tblJugadoresMouseClicked

    private void cbxEquipoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEquipoJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEquipoJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTorneo().setVisible(true);
            }
        });
    }
    
    public void llenarTablaMunicipios(){
        ArrayList<Municipio> listaMunicipios = controlador.SelectMunicipios();
        int filas = listaMunicipios.size();
        int columnas = 2;
        Object[][] datos = new Object[filas][columnas];
        int i = 0;
        for (Municipio municipio : listaMunicipios){
            datos[i][0] = municipio.id;
            datos[i][1] = municipio.nombre;
            i++;
        }
        Object[] encabezados = {"Id", "Nombre"};
        DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
        tblMunicipios.setModel(modelo);
    }
    
      
    public void llenarTablaEquipos(){
        ArrayList<Equipo> listaEquipos = controlador.SelectEquipos();
        int filas = listaEquipos.size();
        int columnas = 4;
        Object[][] datos = new Object[filas][columnas];
        int i = 0;
        for (Equipo equipo : listaEquipos){
            datos[i][0] = equipo.id;
            datos[i][1] = equipo.nombre;
            datos[i][2] = equipo.dt;
            Municipio municipio = controlador.findMunicipio(equipo.id_municipio);
            datos[i][3] = municipio.nombre;
            i++;
        }
        Object[] encabezados = {"Id", "Nombre", "DT", "Municipio"};
        DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
        tblEquipos.setModel(modelo);
    }
    public void llenarTablaPosiciones(){
        ArrayList<Posicion> listaPosiciones = posicionController.SelectPosicion();
        int filas = listaPosiciones.size();
        int columnas = 2;
        Object[][] datos = new Object[filas][columnas];
        int i = 0;
        for (Posicion posicion : listaPosiciones){
            datos[i][0] = posicion.id;
            datos[i][1] = posicion.nombre;
            i++;
        }
        Object[] encabezados = {"Id", "Nombre"};
        DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
        tblPosiciones.setModel(modelo);
    }
    
    public void llenarTablaJugadores(){
        ArrayList<Jugador> listaJugadores = jugadorController.SelectJugador();
        int filas = listaJugadores.size();
        int columnas = 4;
        Object[][] datos = new Object[filas][columnas];
        int i = 0;
        for (Jugador jugador : listaJugadores){
            datos[i][0] = jugador.id;
            datos[i][1] = jugador.nombre;
            datos[i][2] = jugador.numero;
            Equipo equipo = controlador.findEquipo(jugador.id_equipo);
            datos[i][3] = equipo.nombre;
            Posicion posicion = posicionController.findPosicion(jugador.id_posicion);
            datos[i][4] = posicion.nombre;
            i++;
        }
        Object[] encabezados = {"Id", "Nombre", "Numero", "Equipo", "Posicion"};
        DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
        tblJugadores.setModel(modelo);
    }
    
    public void llenarComboMunicipios(){
        ArrayList<Municipio> listaMunicipios = controlador.SelectMunicipios();
        DefaultComboBoxModel modeloMunicipios = new DefaultComboBoxModel();
        for (Municipio municipio : listaMunicipios){
            modeloMunicipios.addElement(municipio);
        }
        cbxMunicipios.setModel(modeloMunicipios);
    }

    public void llenarComboEquipos(){
        ArrayList<Equipo> listaEquipos = controlador.SelectEquipos();
        DefaultComboBoxModel modeloEquipos = new DefaultComboBoxModel();
        for (Equipo equipo : listaEquipos){
            modeloEquipos.addElement(equipo);
        }
        cbxEquipoJugador.setModel(modeloEquipos);
    }
        
    public void llenarComboPosiciones(){
        ArrayList<Posicion> listaPosiciones = posicionController.SelectPosicion();
        DefaultComboBoxModel modeloPosiciones = new DefaultComboBoxModel();
        for (Posicion posicion : listaPosiciones){
            modeloPosiciones.addElement(posicion);
        }
        cbxPosicionJugador.setModel(modeloPosiciones);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEquipo;
    private javax.swing.JButton btnActualizarJugador;
    private javax.swing.JButton btnActualizarMunicipio;
    private javax.swing.JButton btnActualizarPosicion;
    private javax.swing.JButton btnBuscarEquipo;
    private javax.swing.JButton btnBuscarJugador;
    private javax.swing.JButton btnBuscarMunicipio;
    private javax.swing.JButton btnBuscarPosicion;
    private javax.swing.JButton btnCrearEquipo;
    private javax.swing.JButton btnCrearJugador;
    private javax.swing.JButton btnCrearMunicipio;
    private javax.swing.JButton btnCrearPosicion;
    private javax.swing.JButton btnEliminarEquipo;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnEliminarMunicipio;
    private javax.swing.JButton btnEliminarPosicion;
    private javax.swing.JComboBox<String> cbxEquipoJugador;
    private javax.swing.JComboBox<String> cbxMunicipios;
    private javax.swing.JComboBox<String> cbxPosicionJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jpEquipo;
    private javax.swing.JPanel jpJugador;
    private javax.swing.JPanel jpMunicipo;
    private javax.swing.JPanel jpMunicipo1;
    private javax.swing.JPanel jpPosicion;
    private javax.swing.JTabbedPane jpTorneo;
    private javax.swing.JLabel lbDtEquipo;
    private javax.swing.JLabel lbEquipoJugador;
    private javax.swing.JLabel lbIdEquipo;
    private javax.swing.JLabel lbIdJugador;
    private javax.swing.JLabel lbIdMunicipio;
    private javax.swing.JLabel lbIdPosicion;
    private javax.swing.JLabel lbMunicipioEquipo;
    private javax.swing.JLabel lbNombreEquipo;
    private javax.swing.JLabel lbNombreJugador;
    private javax.swing.JLabel lbNombreMunicipio;
    private javax.swing.JLabel lbNombrePosicion;
    private javax.swing.JLabel lbNumeroJugador;
    private javax.swing.JLabel lbPosicionJugador;
    private javax.swing.JTable tblEquipos;
    private javax.swing.JTable tblJugadores;
    private javax.swing.JTable tblMunicipios;
    private javax.swing.JTable tblPosiciones;
    private javax.swing.JTextField txtDtEquipo;
    private javax.swing.JTextField txtIdEquipo;
    private javax.swing.JTextField txtIdJugador;
    private javax.swing.JTextField txtIdMunicipio;
    private javax.swing.JTextField txtIdPosicion;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtNombreMunicipio;
    private javax.swing.JTextField txtNombrePosicion;
    private javax.swing.JTextField txtNumeroJugador;
    // End of variables declaration//GEN-END:variables
}
