/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TorneoController;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Equipo;
import model.Municipio;

/**
 *
 * @author washi
 */
public class FrmTorneo extends javax.swing.JFrame {

    /**
     * Creates new form FrmTorneo
     */
    public FrmTorneo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTorneo = new javax.swing.JTabbedPane();
        jpMunicipo = new javax.swing.JPanel();
        lbIdMunicipio = new javax.swing.JLabel();
        lbNombreMunicipio = new javax.swing.JLabel();
        txtIdMunicipio = new javax.swing.JTextField();
        txtNombreMunicipio = new javax.swing.JTextField();
        btnCrearMunicipio = new javax.swing.JButton();
        btnBuscarMunicipio = new javax.swing.JButton();
        btnActualizarMunicipio = new javax.swing.JButton();
        btnEliminarMunicipio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMunicipios = new javax.swing.JTable();
        jpEquipo = new javax.swing.JPanel();
        lbIdEquipo = new javax.swing.JLabel();
        lbNombreEquipo = new javax.swing.JLabel();
        lbDtEquipo = new javax.swing.JLabel();
        lbMunicipioEquipo = new javax.swing.JLabel();
        txtIdEquipo = new javax.swing.JTextField();
        txtNombreEquipo = new javax.swing.JTextField();
        txtDtEquipo = new javax.swing.JTextField();
        cbxMunicipios = new javax.swing.JComboBox<>();
        btnCrearEquipo = new javax.swing.JButton();
        btnBuscarEquipo = new javax.swing.JButton();
        btnActualizarEquipo = new javax.swing.JButton();
        btnEliminarEquipo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEquipos = new javax.swing.JTable();
        jpPosicion = new javax.swing.JPanel();
        jpJugador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpTorneoMouseClicked(evt);
            }
        });

        lbIdMunicipio.setText("Id Municipio");

        lbNombreMunicipio.setText("Nombre Municipio");

        btnCrearMunicipio.setText("Crear");
        btnCrearMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMunicipioActionPerformed(evt);
            }
        });

        btnBuscarMunicipio.setText("Buscar");
        btnBuscarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMunicipioActionPerformed(evt);
            }
        });

        btnActualizarMunicipio.setText("Actualizar");
        btnActualizarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMunicipioActionPerformed(evt);
            }
        });

        btnEliminarMunicipio.setText("Eliminar");
        btnEliminarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMunicipioActionPerformed(evt);
            }
        });

        tblMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMunicipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMunicipiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMunicipios);

        javax.swing.GroupLayout jpMunicipoLayout = new javax.swing.GroupLayout(jpMunicipo);
        jpMunicipo.setLayout(jpMunicipoLayout);
        jpMunicipoLayout.setHorizontalGroup(
            jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMunicipoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMunicipoLayout.createSequentialGroup()
                        .addComponent(lbIdMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpMunicipoLayout.createSequentialGroup()
                        .addComponent(lbNombreMunicipio)
                        .addGap(6, 6, 6)))
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombreMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(txtIdMunicipio))
                .addGap(18, 18, 18)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMunicipoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMunicipio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMunicipoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBuscarMunicipio)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMunicipoLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        jpMunicipoLayout.setVerticalGroup(
            jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMunicipoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdMunicipio)
                    .addComponent(txtIdMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearMunicipio)
                    .addComponent(btnBuscarMunicipio))
                .addGap(18, 18, 18)
                .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreMunicipio)
                    .addComponent(txtNombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarMunicipio)
                    .addComponent(btnEliminarMunicipio))
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(jpMunicipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMunicipoLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        jpTorneo.addTab("Municipio", jpMunicipo);

        lbIdEquipo.setText("Id equipo");

        lbNombreEquipo.setText("Nombre Equipo");

        lbDtEquipo.setText("D.T. Equipo");

        lbMunicipioEquipo.setText("Municipio Equipo");

        cbxMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMunicipiosActionPerformed(evt);
            }
        });

        btnCrearEquipo.setText("Crear");
        btnCrearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEquipoActionPerformed(evt);
            }
        });

        btnBuscarEquipo.setText("Buscar");
        btnBuscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEquipoActionPerformed(evt);
            }
        });

        btnActualizarEquipo.setText("Actualizar");
        btnActualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEquipoActionPerformed(evt);
            }
        });

        btnEliminarEquipo.setText("Borrar");
        btnEliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEquipoActionPerformed(evt);
            }
        });

        tblEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEquiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEquipos);

        javax.swing.GroupLayout jpEquipoLayout = new javax.swing.GroupLayout(jpEquipo);
        jpEquipo.setLayout(jpEquipoLayout);
        jpEquipoLayout.setHorizontalGroup(
            jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEquipoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEquipoLayout.createSequentialGroup()
                        .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreEquipo)
                            .addComponent(lbDtEquipo))
                        .addGap(18, 18, 18)
                        .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEquipoLayout.createSequentialGroup()
                                .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarEquipo))
                            .addComponent(txtDtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarEquipo)
                            .addGroup(jpEquipoLayout.createSequentialGroup()
                                .addComponent(lbIdEquipo)
                                .addGap(44, 44, 44)
                                .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnBuscarEquipo)))
                        .addGroup(jpEquipoLayout.createSequentialGroup()
                            .addComponent(lbMunicipioEquipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jpEquipoLayout.setVerticalGroup(
            jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEquipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdEquipo)
                    .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearEquipo)
                    .addComponent(btnBuscarEquipo))
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreEquipo)
                    .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarEquipo)
                    .addComponent(btnEliminarEquipo))
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDtEquipo)
                    .addComponent(txtDtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMunicipioEquipo)
                    .addComponent(cbxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jpTorneo.addTab("Equipo", jpEquipo);

        javax.swing.GroupLayout jpPosicionLayout = new javax.swing.GroupLayout(jpPosicion);
        jpPosicion.setLayout(jpPosicionLayout);
        jpPosicionLayout.setHorizontalGroup(
            jpPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jpPosicionLayout.setVerticalGroup(
            jpPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jpTorneo.addTab("Posicion", jpPosicion);

        javax.swing.GroupLayout jpJugadorLayout = new javax.swing.GroupLayout(jpJugador);
        jpJugador.setLayout(jpJugadorLayout);
        jpJugadorLayout.setHorizontalGroup(
            jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jpJugadorLayout.setVerticalGroup(
            jpJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jpTorneo.addTab("Jugador", jpJugador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    TorneoController controlador = new TorneoController();
    
    private void formWindowOpened(java.awt.event.WindowEvent evt){
        llenarTablaMunicipios();
        llenarComboMunicipios();
        llenarTablaEquipos();
    }
    
    private void tblMunicipiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMunicipiosMouseClicked
        // TODO add your handling code here:
        int fila = tblMunicipios.getSelectedRow();
        int id = (int) tblMunicipios.getValueAt(fila, 0);
        Municipio municipio = controlador.findMunicipio(id);
        txtIdMunicipio.setText("" + municipio.id);
        txtNombreMunicipio.setText(municipio.nombre);
        llenarTablaMunicipios();
    }//GEN-LAST:event_tblMunicipiosMouseClicked

    private void btnCrearMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMunicipioActionPerformed
        String nombre = txtNombreMunicipio.getText();
        boolean seInserto = controlador.insertMunicipio(nombre);
        if (seInserto){
            JOptionPane.showMessageDialog(this,"el municipio se inserto correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al insertar el municipio");
        }
        llenarTablaMunicipios(); 
        llenarComboMunicipios();
    }//GEN-LAST:event_btnCrearMunicipioActionPerformed

    private void btnBuscarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMunicipioActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdMunicipio.getText());
        Municipio municipio = controlador.findMunicipio(id);
        if(municipio == null){
            JOptionPane.showMessageDialog(this, "El municipio no fue encontrado!");
        }else{
            txtNombreMunicipio.setText(municipio.nombre);
        }
    }//GEN-LAST:event_btnBuscarMunicipioActionPerformed

    private void btnActualizarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMunicipioActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdMunicipio.getText());
        String nombre = txtNombreMunicipio.getText();
        boolean seActualizo = controlador.updateMunicipio(id, nombre);
        if (seActualizo){
            JOptionPane.showMessageDialog(this, "El municipio se actualizó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error el municipio no se actualizó!");
        }
        llenarTablaMunicipios(); 
        llenarComboMunicipios();
    }//GEN-LAST:event_btnActualizarMunicipioActionPerformed

    private void btnEliminarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMunicipioActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdMunicipio.getText());
        if (controlador.deleteMunicipio(id)){
            JOptionPane.showMessageDialog(this, "El municipio se eliminó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error el municipio no se eliminó!");
        }
        llenarTablaMunicipios();           
        llenarComboMunicipios();
    }//GEN-LAST:event_btnEliminarMunicipioActionPerformed

    private void btnCrearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEquipoActionPerformed
        // TODO add your handling code here:
        
        String nombre = txtNombreEquipo.getText();
        String dt = txtDtEquipo.getText();
        Municipio municipio = (Municipio)(cbxMunicipios.getSelectedItem());
        int id_municipio = municipio.id;
        boolean seInserto = controlador.insertEquipo(nombre, dt, id_municipio);
        if (seInserto){
            JOptionPane.showMessageDialog(this,"El equipo se inserto correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al insertar el equipo");
        }
        
        llenarTablaEquipos();
       
    }//GEN-LAST:event_btnCrearEquipoActionPerformed

    private void cbxMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMunicipiosActionPerformed
        // TODO add your handling code here:
        //llenarComboMunicipios();
    }//GEN-LAST:event_cbxMunicipiosActionPerformed

    private void tblEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquiposMouseClicked
        // TODO add your handling code here:
        int fila = tblEquipos.getSelectedRow();
        int id = (int) tblEquipos.getValueAt(fila, 0);
        Equipo equipo = controlador.findEquipo(id);
        txtIdEquipo.setText("" + equipo.id);
        txtNombreEquipo.setText(equipo.nombre);
        txtDtEquipo.setText(equipo.dt);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbxMunicipios.getModel();
        for(int i = 0; i < modelo.getSize(); i++){
            Municipio municipio = (Municipio) modelo.getElementAt(i);
            if(municipio.id == equipo.id_municipio){
                cbxMunicipios.setSelectedItem(municipio);
                break;
            }
        }
        
    }//GEN-LAST:event_tblEquiposMouseClicked

    private void jpTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTorneoMouseClicked
        // TODO add your handling code here:
        llenarTablaMunicipios();
        llenarComboMunicipios();
        llenarTablaEquipos();


    }//GEN-LAST:event_jpTorneoMouseClicked

    private void btnBuscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEquipoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdEquipo.getText());
        Equipo equipo = controlador.findEquipo(id);
        txtNombreEquipo.setText(equipo.nombre);
        txtDtEquipo.setText(equipo.dt);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbxMunicipios.getModel();
        for(int i = 0; i < modelo.getSize(); i++){
            Municipio municipio = (Municipio) modelo.getElementAt(i);
            if(municipio.id == equipo.id_municipio){
                cbxMunicipios.setSelectedItem(municipio);
                break;
            }
        }
    }//GEN-LAST:event_btnBuscarEquipoActionPerformed

    
      
        
    private void btnActualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEquipoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdEquipo.getText());
        String nombre = txtNombreEquipo.getText();
        String dt = txtDtEquipo.getText();
        Municipio municipio = (Municipio)(cbxMunicipios.getSelectedItem());
        int id_municipio = municipio.id;
        boolean seActualizo = controlador.updateEquipo(id, nombre, dt, id_municipio);
        if (seActualizo){
            JOptionPane.showMessageDialog(this,"El equipo se actualizó correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Hubo un error al actualizar el equipo");
        }
        
        llenarTablaEquipos();        llenarTablaEquipos();

    }//GEN-LAST:event_btnActualizarEquipoActionPerformed

    private void btnEliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEquipoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdEquipo.getText());
        if (controlador.deleteEquipo(id)){
            JOptionPane.showMessageDialog(this, "El Equipo se eliminó!");
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error el Equipo no se eliminó!");
        }
        llenarTablaEquipos();
        llenarComboMunicipios();
    }//GEN-LAST:event_btnEliminarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTorneo().setVisible(true);
            }
        });
    }
    
    public void llenarTablaMunicipios(){
        ArrayList<Municipio> listaMunicipios = controlador.SelectMunicipios();
        int filas = listaMunicipios.size();
        int columnas = 2;
        Object[][] datos = new Object[filas][columnas];
        int i = 0;
        for (Municipio municipio : listaMunicipios){
            datos[i][0] = municipio.id;
            datos[i][1] = municipio.nombre;
            i++;
        }
        Object[] encabezados = {"Id", "Nombre"};
        DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
        tblMunicipios.setModel(modelo);
    }
    
    public void llenarComboMunicipios(){
        ArrayList<Municipio> listaMunicipios = controlador.SelectMunicipios();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Municipio municipio : listaMunicipios){
            modelo.addElement(municipio);
        }
        cbxMunicipios.setModel(modelo);
    }

    public void llenarTablaEquipos(){
        ArrayList<Equipo> listaEquipos = controlador.SelectEquipos();
        int filas = listaEquipos.size();
        int columnas = 4;
        Object[][] datos = new Object[filas][columnas];
        int i = 0;
        for (Equipo equipo : listaEquipos){
            datos[i][0] = equipo.id;
            datos[i][1] = equipo.nombre;
            datos[i][2] = equipo.dt;
            Municipio municipio = controlador.findMunicipio(equipo.id_municipio);
            datos[i][3] = municipio.nombre;
            i++;
        }
        Object[] encabezados = {"Id", "Nombre", "DT", "Municipio"};
        DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
        tblEquipos.setModel(modelo);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEquipo;
    private javax.swing.JButton btnActualizarMunicipio;
    private javax.swing.JButton btnBuscarEquipo;
    private javax.swing.JButton btnBuscarMunicipio;
    private javax.swing.JButton btnCrearEquipo;
    private javax.swing.JButton btnCrearMunicipio;
    private javax.swing.JButton btnEliminarEquipo;
    private javax.swing.JButton btnEliminarMunicipio;
    private javax.swing.JComboBox<String> cbxMunicipios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpEquipo;
    private javax.swing.JPanel jpJugador;
    private javax.swing.JPanel jpMunicipo;
    private javax.swing.JPanel jpPosicion;
    private javax.swing.JTabbedPane jpTorneo;
    private javax.swing.JLabel lbDtEquipo;
    private javax.swing.JLabel lbIdEquipo;
    private javax.swing.JLabel lbIdMunicipio;
    private javax.swing.JLabel lbMunicipioEquipo;
    private javax.swing.JLabel lbNombreEquipo;
    private javax.swing.JLabel lbNombreMunicipio;
    private javax.swing.JTable tblEquipos;
    private javax.swing.JTable tblMunicipios;
    private javax.swing.JTextField txtDtEquipo;
    private javax.swing.JTextField txtIdEquipo;
    private javax.swing.JTextField txtIdMunicipio;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtNombreMunicipio;
    // End of variables declaration//GEN-END:variables
}
